name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  npm-publish:
    name: publish-npm
    runs-on: ubuntu-latest
    environment: Publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Typecheck
        run: yarn tsc

      - name: Build package
        run: yarn build

      - name: Publish to npm
        run: npm publish --provenance --access public
